name: dragonballapi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_dragonballapi.webp
    - assets/effects/flash1.png
    - assets/effects/flash2.png
    - assets/effects/flash3.png
    - assets/images/goku_jiren.png
    - assets/images/torneo.jpg
    - assets/esferas_dragon/esfera_1.png
    - assets/esferas_dragon/esfera_2.png
    - assets/esferas_dragon/esfera_3.png
    - assets/esferas_dragon/esfera_4.png
    - assets/esferas_dragon/esfera_5.png
    - assets/esferas_dragon/esfera_6.png
    - assets/esferas_dragon/esfera_7.png
