name: dragonballapi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  youtube_player_flutter: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_dragonballapi.webp
    - assets/effects/flash1.png
    - assets/effects/flash2.png
    - assets/effects/flash3.png
    - assets/images/gogeta.webp
    - assets/images/Shen_Long.webp
    - assets/images/jiren.webp
    - assets/images/goku_jiren.png
    - assets/images/slider1.webp
    - assets/images/slider2.jpg
    - assets/images/laterales/slider2_broly.jpg
    - assets/images/laterales/slider2_goku_black.jpg
    - assets/images/laterales/slider2_goku4.jpg
    - assets/images/laterales/slider2_vegeta4.jpg
    - assets/images/laterales/slider2_ultra.jpg
    - assets/images/laterales/slider2_vegito.jpg
    - assets/images/slider3.webp
    - assets/images/slider4.webp
    - assets/images/slider5.jpg
    - assets/images/slider6.jpg
    - assets/esferas_dragon/esfera_1.png
    - assets/esferas_dragon/esfera_2.png
    - assets/esferas_dragon/esfera_3.png
    - assets/esferas_dragon/esfera_4.png
    - assets/esferas_dragon/esfera_5.png
    - assets/esferas_dragon/esfera_6.png
    - assets/esferas_dragon/esfera_7.png
    